parameters:
  thrift.client.class: Overblog\ThriftBundle\Client\ThriftClient
  thrift.compile_warmer.class: Overblog\ThriftBundle\CacheWarmer\ThriftCompileCacheWarmer
  thrift.factory: Overblog\ThriftBundle\Factory\ThriftFactory

services:
  thrift.compile_warmer:
    class: %thrift.compile_warmer.class%
    arguments: [@service_container, %thrift.config.compiler.path%, %thrift.config.services%]
    tags:
      - { name: "kernel.cache_warmer", priority: "10" }

  thrift.factory:
    class: %thrift.factory%
    arguments: [%thrift.config.services%, @event_dispatcher, %kernel.debug%]
